[build]
  base = "lex-chat"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://orgesskura--lex-fridman-podcast-rag-web-app.modal.run"